### ISSUE TITLE
Design a FAQ Page

### ISSUE THREAD

**Issue by ypratham** [PH-DC/HackPDC#12]
- Questions to be answered: 
--- Q. How can we participate ?
--- Q. Is this hackathon hosted by Pillai HOC Polytechnic ?
--- Q. What are the basic judging criteria ?

**Comment by Deepkk-9** [comment]
I am solving this issue too

**Comment by ypratham** [comment]
Go for it

**Comment by saloni427** [comment]
i'd like to do it.

**Comment by SiddhiT28** [comment]
I am also interested in solving this issue.

**Comment by ypratham** [comment]
You guys can do in collaboration 👍

**Comment by cmulay** [comment]
Merged with PR #19
